{% set version = "0.2.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sweep
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sweep_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sweep/sweep_{{ version }}.tar.gz
  sha256: cb1164cd87757b9e9c97c8621748ced84bb861635cfdc121f2463e7fd99c3ac1

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-broom >=0.5.6
    - r-dplyr >=1.0.0
    - r-forecast >=8.0
    - r-lubridate >=1.6.0
    - r-rlang
    - r-tibble >=1.2
    - r-tidyquant
    - r-tidyr >=1.0.0
    - r-tidyverse
    - r-timetk >=2.1.0
  run:
    - r-base
    - r-broom >=0.5.6
    - r-dplyr >=1.0.0
    - r-forecast >=8.0
    - r-lubridate >=1.6.0
    - r-rlang
    - r-tibble >=1.2
    - r-tidyquant
    - r-tidyr >=1.0.0
    - r-tidyverse
    - r-timetk >=2.1.0

test:
  commands:
    - $R -e "library('sweep')"           # [not win]
    - "\"%R%\" -e \"library('sweep')\""  # [win]

about:
  home: https://github.com/business-science/sweep
  license: GPL-3.0-or-later
  summary: Tidies up the forecasting modeling and prediction work flow, extends the 'broom' package with 'sw_tidy', 'sw_glance', 'sw_augment', and 'sw_tidy_decomp' functions for various forecasting models, and enables converting 'forecast' objects to "tidy" data frames with 'sw_sweep'.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - mxr-conda
    - oblute
    - rluria14
    - benhuff

# The original CRAN metadata for this package was:
# Package: sweep
# Type: Package
# Title: Tidy Tools for Forecasting
# Version: 0.2.2
# Date: 2019-10-08
# Authors@R: c( person("Matt", "Dancho", email = "mdancho@business-science.io", role = c("aut", "cre")), person("Davis", "Vaughan", email = "dvaughan@business-science.io", role = c("aut")) )
# Maintainer: Matt Dancho <mdancho@business-science.io>
# Description: Tidies up the forecasting modeling and prediction work flow, extends the 'broom' package with 'sw_tidy', 'sw_glance', 'sw_augment', and 'sw_tidy_decomp' functions for various forecasting models, and enables converting 'forecast' objects to "tidy" data frames with 'sw_sweep'.
# URL: https://github.com/business-science/sweep
# BugReports: https://github.com/business-science/sweep/issues
# License: GPL (>= 3)
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 3.3.0)
# Imports: broom (>= 0.4.2), dplyr (>= 0.7.0), forecast (>= 8.0), lazyeval (>= 0.2.0), lubridate (>= 1.6.0), tibble (>= 1.2), tidyr (>= 1.0.0), timetk (>= 0.1.0)
# Suggests: forcats, knitr, rmarkdown, testthat, purrr, readr, robets, stringr, scales, tidyquant, tidyverse, fracdiff
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-10-08 12:45:22 UTC; mdancho
# Author: Matt Dancho [aut, cre], Davis Vaughan [aut]
# Repository: CRAN
# Date/Publication: 2019-10-08 13:50:02 UTC
# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
