bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: sE9JOSzz8O8r5fcZO+NzlKsc8sxyjC+sCihsqbN+/hcLatJ08jhiHOo6cpa0wANyO0vtFW0vMMd9jjT1VRNKGRvAIZ1IXheVfREBeMp2UTEl3Mw39OoFl78Lj7dOZXLCIyGVYiUfsPg+dojFhqW9Q/6T7ot1vfFzdLrjTSCObm0Q6bKHQnnZZDzJMC5T8TAa3MNN3wfgEoJ+Lo8C2WAc0JW/6bwigV1k/xlfwT/2jUjVmZxJbIOIHZRqtssW+Ug0IRki+gV0Bh1Oh/gZd6wzdcwGWmkfIlWZsthZuUjFIg/k6duDmzjVXk3OkajCHPr4/XSX7+X+WOElTFAQ+O92Wqtw7YqOt0Cf/MmxI3mm6LCZ3q1EKxotvwUQHvQIqBp6mbO44Z+Qd/rfEvS35uaQoOEo5V1/lq+RkiMTsZgdX2E7q607ie0m8DCqtNv+2TcifPjxRX1HVRb5iqnz3HQRS6pAjF8vi6jgx66g5+H3HRnIX1vFizJvCUurbMB+Tv0OTJg9GfNnO/yJhkJxNSsW+QQoG7u4F7oKdQnJbvDCSGFxR0r9T62ZqJkyHtjl+5Vqtr1Wgx/6375t65ToYYZ0fkdG7t2vwGMgR2k6O3WnJIM8FdQXLu1L9NBEN71yqg9/xsyHbJCQBIE9031LIziSBpXz/sIrIJPvNKaIWC+t3UM=
conda_forge_output_validation: true
